# Define symbolic link sources and targets
$DOTFILES_DIR/ghostty:$HOME/.config/ghostty
$DOTFILES_DIR/tmux/tmux.conf:$HOME/.config/tmux/tmux.conf
$DOTFILES_DIR/tmux/README.md:$HOME/.config/tmux/README.md
$DOTFILES_DIR/nvim:$HOME/.config/nvim
$DOTFILES_DIR/zsh/.zshrc:$HOME/.zshrc
$DOTFILES_DIR/zsh/.zprofile:$HOME/.zprofile
$DOTFILES_DIR/zsh/aliases.zsh:$HOME/.config/zsh/aliases.zsh
$DOTFILES_DIR/zsh/completions.zsh:$HOME/.config/zsh/completions.zsh
$DOTFILES_DIR/zsh/exports.zsh:$HOME/.config/zsh/exports.zsh
$DOTFILES_DIR/zsh/functions.zsh:$HOME/.config/zsh/functions.zsh
$DOTFILES_DIR/zsh/p10k.zsh:$HOME/.config/zsh/p10k.zsh
$DOTFILES_DIR/zsh/paths.zsh:$HOME/.config/zsh/paths.zsh
$DOTFILES_DIR/zsh/plugins.zsh:$HOME/.config/zsh/plugins.zsh
$DOTFILES_DIR/zsh/syntax-highlighting.zsh:$HOME/.config/zsh/syntax-highlighting.zsh
$DOTFILES_DIR/zsh/tools.zsh:$HOME/.config/zsh/tools.zsh
$DOTFILES_DIR/tmux/scripts/ram_percent.sh:$HOME/.config/tmux/plugins/tmux/scripts/ram_percent.sh
$DOTFILES_DIR/tmux/scripts/weather.sh:$HOME/.config/tmux/plugins/tmux/scripts/weather.sh
$DOTFILES_DIR/git/config:$HOME/.config/git/config
$DOTFILES_DIR/yazi/yazi.toml:$HOME/.config/yazi/yazi.toml
$DOTFILES_DIR/yazi/theme.toml:$HOME/.config/yazi/theme.toml
